name: Build and Push Docker Images to Docker Hub
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  DOCKER_USERNAME: bigrock4522
  MOBILE_IMAGE_NAME: refonte_genai_mobile_frontend  # Name for the mobile frontend Docker image
  WEB_IMAGE_NAME: refonte_genai_web_frontend_backend  # Name for the web frontend-backend Docker image

defaults:
  run:
    shell: bash

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Step to handle versioning
      - name: Read and increment version
        id: versioning
        run: |
          # Check if VERSION file exists, otherwise start with 1.0
          if [ ! -f VERSION ]; then
            echo "v1.0" > VERSION
          fi

          # Read the current version
          CURRENT_VERSION=$(cat VERSION)

          # Extract major and minor version numbers
          MAJOR=$(echo $CURRENT_VERSION | cut -d '.' -f 1 | sed 's/v//')
          MINOR=$(echo $CURRENT_VERSION | cut -d '.' -f 2)

          # Increment minor version number
          NEW_MINOR=$((MINOR + 1))

          # Combine major and new minor version
          NEW_VERSION="v${MAJOR}.${NEW_MINOR}"

          # Update the VERSION file
          echo $NEW_VERSION > VERSION

          # Output the new version as an action output
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      # Build and push the mobile app Docker image
      - name: Build and push mobile frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./mobile_app/frontend  # Directory containing the mobile Dockerfile
          file: ./mobile_app/frontend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.MOBILE_IMAGE_NAME }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.MOBILE_IMAGE_NAME }}:${{ env.NEW_VERSION }}

      # # Build and push the web app Docker image
      # - name: Build and push web frontend-backend Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./web_app/frontend_backend  # Directory containing the web Dockerfile
      #     file: ./web_app/frontend_backend/Dockerfile
      #     push: true
      #     tags: |
      #       ${{ env.DOCKER_USERNAME }}/${{ env.WEB_IMAGE_NAME }}:latest
      #       ${{ env.DOCKER_USERNAME }}/${{ env.WEB_IMAGE_NAME }}:${{ env.NEW_VERSION }}

      - name: Commit updated version
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Bump version to ${{ env.NEW_VERSION }}"
          git push
